### ISSUE TITLE
Windows Defender 

### ISSUE THREAD

**Issue by TCG137** [DixelU/SAFC#2]
Windows Defender keeps me from downloading the x64 version of SAFC.

**Comment by DixelU** [comment]
Welp, it's almost a year since it was opened. Is it still relevant?

**Comment by DixelU** [comment]
Might get resolved once I start using libarchive to unpack the SAFC's updates

**Comment by DixelU** [comment]
should be fixed by https://github.com/DixelU/SAFC/releases/tag/v1.3.2.0
