### ISSUE TITLE
Selection start doesn't always work properly.

### ISSUE THREAD

**Issue by GenericCherrySwitch** [DixelU/SAFC#3]
If you set the selection start to any tick, but keep the section length to -1 as it does by default when loading a MIDI in SAFC, SAFC will process the MIDI as if the selection start parameter was always set to zero.

**Comment by DixelU** [comment]
@GenericCherrySwitch  Hi!
There's a pre release testing unrolling rn. For now the pre release SAFC processes midis roughly 1.8 times slower than 1.2.5.1. Still figuring out the ways to minimize the impact of new abstraction level added inside. 

You could join the discord server, where you'll be able to get that version to play around. :P

**Comment by DixelU** [comment]
Merged, will be out in 1.3 :)
