### ISSUE TITLE
The merged .mid file doesn't show any notes

### ISSUE THREAD

**Issue by KRUTIKOVARTEM2009** [DixelU/SAFC#6]
PLEASE FIX THIS!!!!!!1

**Comment by DixelU** [comment]
It's kinda weird how i missed this ticket
Could you elaborate? @KRUTIKOVARTEM2009

**Comment by DixelU** [comment]
It would be increasingly helpful if you provided some specific MIDIs that you tried to merge

**Comment by KRUTIKOVARTEM2009** [comment]
I tried to merge all MIDIs in my downloads(now a lot is deleted)

**Comment by DixelU** [comment]
It might be just the fact that either you ran out of space on your hard drive, or available RAM.
I can't reproduce it yet :p

**Comment by DixelU** [comment]
Can you reproduce it now though?

**Comment by KRUTIKOVARTEM2009** [comment]
still can't

**Comment by KRUTIKOVARTEM2009** [comment]
still can't

**Comment by DixelU** [comment]
> Now I still can reproduce this problem, even after updating.

It would greatly help if you attached midis you used to reproduce the problem though 👀
