### ISSUE TITLE
Negative offsets keeps original length of the output

### ISSUE THREAD

**Issue by GenericCherrySwitch** [DixelU/SAFC#8]
![image](https://github.com/DixelU/SAFC/assets/44690814/2a44db39-9ea9-4599-910b-628d034c09e0)
See image above; negative offsets still retains the original length of the MIDI but discards all data below the offset.

**Comment by DixelU** [comment]
Probably fixed in https://github.com/DixelU/SAFC/releases/tag/v1.4.1.1

**Comment by GenericCherrySwitch** [comment]
Confirmed, this bug is no longer present.
